site_name: structured-logprobs
repo_url: https://github.com/arena-ai/structured-logprobs
site_url: https://arena-ai.github.io/structured-logprobs
site_description: Logprobs for OpenAI Structured Outputs
site_author: Sarus Technologies
edit_uri: edit/main/docs/
repo_name: arena-ai/structured-logprobs
copyright: Maintained by <a href="https://arena-ai.com">arena-ai</a>.

nav:
  - Home: index.md
  - Getting started: notebooks/notebook.ipynb
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [structured_logprobs]
  - mkdocs-jupyter

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arena-ai/structured-logprobs
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/structured-logprobs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
